language: python
matrix:
  include:
  # generic checks
  - python: "3.9"
    env: TOX_ENV=flake8
  - python: "3.9"
    env: TOX_ENV=check_rst
  - python: "3.9"
    env: TOX_ENV=coverage
  # RHEL 8 support
  - python: "3.6"
    env: TOX_ENV=py36-django22
  - python: "3.6"
    env: TOX_ENV=py36-django22
    arch: ppc64le
  # Ubuntu focal and Ubuntu groovy support
  - python: "3.8"
    env: TOX_ENV=py38-django22
  - python: "3.8"
    env: TOX_ENV=py38-django22
    arch: ppc64le
  # Debian bullseye and Ubuntu hirsute support
  - python: "3.9"
    env: TOX_ENV=py39-django22
  - python: "3.9"
    env: TOX_ENV=py39-django22
    arch: ppc64le
  # Ubuntu jammy support
  - python: "3.10"
    env: TOX_ENV=py310-django32
  - python: "3.10"
    env: TOX_ENV=py310-django32
    arch: ppc64le
  # Django additional supported version
  - python: "3.9"
    env: TOX_ENV=py39-django32
  - python: "3.10"
    env: TOX_ENV=py310-django40
  - python: "3.10"
    env: TOX_ENV=py310-django41

cache:
  directories:
    - $HOME/.cache/pip/http/
    - $HOME/build/nitmir/django-cas-server/.tox/$TOX_ENV/
install:
  - travis_retry pip install setuptools --upgrade
  - pip install tox $PKGS
  - pip freeze
script:
  - tox -e $TOX_ENV
after_script:
  - cat tox_log/*.log
